// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RexusOps360.API.Data;

#nullable disable

namespace RexusOps360.API.Migrations
{
    [DbContext(typeof(EmsDbContext))]
    partial class EmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RexusOps360.API.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastMaintenance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableQuantity = 4,
                            Barcode = "DEF001",
                            CreatedAt = new DateTime(2024, 6, 1, 8, 30, 0, 0, DateTimeKind.Utc),
                            Location = "Main Station",
                            Name = "Defibrillator",
                            Quantity = 5,
                            Status = "Available",
                            Type = "Medical"
                        },
                        new
                        {
                            Id = 2,
                            AvailableQuantity = 2,
                            Barcode = "AMB001",
                            CreatedAt = new DateTime(2024, 6, 1, 8, 35, 0, 0, DateTimeKind.Utc),
                            Location = "Downtown Station",
                            Name = "Ambulance",
                            Quantity = 3,
                            Status = "Available",
                            Type = "Transport"
                        },
                        new
                        {
                            Id = 3,
                            AvailableQuantity = 8,
                            Barcode = "RAD001",
                            CreatedAt = new DateTime(2024, 6, 1, 8, 40, 0, 0, DateTimeKind.Utc),
                            Location = "Communication Center",
                            Name = "Radio Communication",
                            Quantity = 10,
                            Status = "Available",
                            Type = "Communication"
                        });
                });

            modelBuilder.Entity("RexusOps360.API.Models.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedResponders")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EquipmentNeeded")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReportedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Priority");

                    b.HasIndex("Status");

                    b.ToTable("Incidents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedResponders = "1",
                            CreatedAt = new DateTime(2024, 6, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cardiac arrest reported at office building",
                            EquipmentNeeded = "Defibrillator,Ambulance",
                            Location = "Downtown Tampa, FL",
                            Priority = "High",
                            ReportedBy = "John Doe",
                            Status = "Active",
                            Type = "Medical Emergency"
                        },
                        new
                        {
                            Id = 2,
                            AssignedResponders = "2,3",
                            CreatedAt = new DateTime(2024, 6, 1, 9, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Multi-vehicle collision on highway",
                            EquipmentNeeded = "Ambulance,Fire Truck",
                            Location = "I-275, Tampa, FL",
                            Priority = "Medium",
                            ReportedBy = "Highway Patrol",
                            Status = "Active",
                            Type = "Traffic Accident"
                        },
                        new
                        {
                            Id = 3,
                            AssignedResponders = "3",
                            CreatedAt = new DateTime(2024, 6, 1, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kitchen fire in residential building",
                            EquipmentNeeded = "Fire Truck,Water Tanker",
                            Location = "West Tampa, FL",
                            Priority = "High",
                            ReportedBy = "Building Manager",
                            Status = "Resolved",
                            Type = "Fire Emergency",
                            UpdatedAt = new DateTime(2024, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("RexusOps360.API.Models.Responder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Specializations")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Role");

                    b.HasIndex("Status");

                    b.ToTable("Responders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNumber = "813-555-0101",
                            CreatedAt = new DateTime(2024, 6, 1, 8, 15, 0, 0, DateTimeKind.Utc),
                            CurrentLocation = "Downtown Tampa",
                            Name = "John Smith",
                            Role = "Paramedic",
                            Specializations = "Cardiac,Trauma",
                            Status = "Available"
                        },
                        new
                        {
                            Id = 2,
                            ContactNumber = "813-555-0102",
                            CreatedAt = new DateTime(2024, 6, 1, 8, 20, 0, 0, DateTimeKind.Utc),
                            CurrentLocation = "Airport Area",
                            Name = "Sarah Johnson",
                            Role = "EMT",
                            Specializations = "Basic Life Support",
                            Status = "Available"
                        },
                        new
                        {
                            Id = 3,
                            ContactNumber = "813-555-0103",
                            CreatedAt = new DateTime(2024, 6, 1, 8, 25, 0, 0, DateTimeKind.Utc),
                            CurrentLocation = "West Tampa",
                            Name = "Mike Davis",
                            Role = "Firefighter",
                            Specializations = "Fire Suppression,Rescue",
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("RexusOps360.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenantId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Tampa, FL",
                            CreatedAt = new DateTime(2024, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@emstampa.com",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "",
                            Phone = "813-555-0001",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Tampa, FL",
                            CreatedAt = new DateTime(2024, 6, 1, 8, 5, 0, 0, DateTimeKind.Utc),
                            Email = "dispatcher@emstampa.com",
                            FullName = "Emergency Dispatcher",
                            IsActive = true,
                            PasswordHash = "",
                            Phone = "813-555-0002",
                            Role = "Dispatcher",
                            Username = "dispatcher"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Tampa, FL",
                            CreatedAt = new DateTime(2024, 6, 1, 8, 10, 0, 0, DateTimeKind.Utc),
                            Email = "responder@emstampa.com",
                            FullName = "Emergency Responder",
                            IsActive = true,
                            PasswordHash = "",
                            Phone = "813-555-0003",
                            Role = "Responder",
                            Username = "responder"
                        });
                });

            modelBuilder.Entity("RexusOps360.API.Services.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("Severity");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
